apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-tracker
  labels:
    app: tracker
spec:
  replicas: 6
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
      - name: tracker
        image: amitb26j/event_tracker:latest
        ports:
        - containerPort: 8080